"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'server',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173',
    cast=Csv()
)

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'server.authentication.ExpiringTokenAuthentication',
    ],
    # El valor de fábrica de DRF es AllowAny: una vista futura sin
    # permission_classes quedaría pública sin que nada avise. Con esto, olvidar
    # la línea cierra en vez de abrir. Lo público se declara — LoginView lo hace.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ] if config('DEBUG', default=False, cast=bool) else [
        'rest_framework.renderers.JSONRenderer',
    ]
}


# ── Correo saliente ───────────────────────────────────────────────────────────
# Solo para avisos técnicos al equipo
CORREO_AVISOS = config('CORREO_AVISOS', default='')
ADMINS = [('MUDAR', CORREO_AVISOS)] if CORREO_AVISOS else []

# Por omisión, el de consola: en desarrollo el aviso se imprime en la terminal en
# vez de enviarse, así que nada sale de la máquina ni hace falta credencial.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# DEFAULT_FROM_EMAIL es el remitente corriente; SERVER_EMAIL, el de los avisos de
# error. Son ajustes distintos y Django no deriva uno del otro.
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Para reconocer los avisos en la bandeja y poder filtrarlos. El espacio final es parte del valor.
EMAIL_SUBJECT_PREFIX = '[MUDAR] '


if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

    # La ruta de los registros es la única de este bloque que difiere entre desarrollo y
    # producción. En el servidor viven en /var/log/mudar, que es donde los busca un
    # administrador y donde apunta fail2ban; en local, el valor por defecto deja todo igual.
    LOG_DIR = Path(config('LOG_DIR', default=BASE_DIR / 'logs'))
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'detallado': {
                'format': '{asctime} {levelname} {name} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'archivo': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': LOG_DIR / 'mudar.log',
                'maxBytes': 5 * 1024 * 1024,
                'backupCount': 3,
                'formatter': 'detallado',
                # Sin esto, la biblioteca abre el archivo con la codificación del sistema: cp1252 en
                # Windows y la del servicio en Linux. Un carácter que no quepa no se degrada, se
                # pierde: emit captura el error y descarta la línea.
                'encoding': 'utf-8',
            },
            # Archivo propio: fail2ban vigila una ruta concreta y le conviene que todo
            # lo que hay en ella sea de su incumbencia.
            'seguridad': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': LOG_DIR / 'seguridad.log',
                'maxBytes': 5 * 1024 * 1024,
                'backupCount': 3,
                'formatter': 'detallado',
                # Misma razón que arriba, y aquí pesa más: fail2ban no bloquea lo que no lee.
                'encoding': 'utf-8',
            },
            # Django engancha este manejador por defecto, pero declarar un logger
            # 'django' propio sustituye esa configuración: sin esta entrada en 'handlers'
            # no saldría ningún aviso.
            'mail_admins': {
                'class': 'django.utils.log.AdminEmailHandler',
                # Solo desde ERROR. Mandar por correo todo lo que entra al registro lo volvería ruido.
                'level': 'ERROR',
                'include_html': False,
            },
        },
        'loggers': {
            'django': {
                'handlers': ['archivo', 'mail_admins'],
                'level': 'WARNING',
            },
            # Sin esta entrada el mensaje sube al logger raíz, que no tiene manejadores,
            # y acaba en la salida de error en lugar de en un archivo.
            'server.seguridad': {
                'handlers': ['seguridad'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
