# Generated by Django 5.2.7 on 2025-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('dom_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField(blank=True)),
                ('orden_produccion', models.IntegerField(blank=True)),
                ('fecha_produccion', models.DateField(blank=True)),
                ('lider_produccion', models.CharField(blank=True, choices=[('SIN_LIDER', '-- Seleccione un lider --'), ('ALEX_AREVALO', 'Alex Arevalo'), ('JULIO_MARTINEZ', 'Julio Martinez'), ('LUIS_MANRIQUE', 'Luis Manrique'), ('JHON_MOTERREY', 'Jhon Monterrey')], max_length=200)),
                ('materia_prima_disponible', models.BooleanField(blank=True, default=False)),
                ('requiere_prealistamiento', models.BooleanField(blank=True, default=False)),
                ('cantidad_elaborada', models.IntegerField(blank=True)),
                ('cantidad_pendiente', models.IntegerField(blank=True)),
                ('necesita_carton', models.BooleanField(blank=True, default=False)),
                ('grafado_fundas', models.BooleanField(blank=True, default=False)),
                ('lider_almacen', models.CharField(blank=True, choices=[('SIN_LIDER', '-- Seleccione un lider --'), ('ALEX_AREVALO', 'Alex Arevalo'), ('JULIO_MARTINEZ', 'Julio Martinez'), ('LUIS_MANRIQUE', 'Luis Manrique'), ('JHON_MOTERREY', 'Jhon Monterrey')], max_length=200)),
                ('fecha_tratamiento', models.DateField(blank=True)),
                ('orden_tratamiento', models.IntegerField(blank=True)),
                ('cliente_recoge', models.BooleanField(blank=True, default=True)),
                ('mudar_entrega', models.BooleanField(blank=True, default=False)),
                ('tratamiento_realizado', models.BooleanField(blank=True, default=False)),
                ('sello_ica', models.BooleanField(blank=True, default=False)),
                ('peso_producto', models.IntegerField(blank=True)),
                ('marcacion_cliente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DomSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dom',
                'db_table': 'dom',
            },
        ),
    ]
