# Generated by Django 5.2.7 on 2025-11-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomSerializer',
        ),
        migrations.AlterModelOptions(
            name='dom',
            options={'verbose_name': 'Dom', 'verbose_name_plural': 'Doms'},
        ),
        migrations.AlterModelTable(
            name='dom',
            table='server_dom',
        ),
    ]
