# Generated by Django 5.2.7 on 2026-03-17 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIT'),
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('familia_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código familia')),
                ('nombre_familia', models.CharField(max_length=100, verbose_name='Nombre familia')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Familia activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familia_creada_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familia de Producto',
                'verbose_name_plural': 'Familias de Producto',
                'db_table': 'familias_producto',
                'ordering': ['nombre_familia'],
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='familia_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='server.familiaproducto', verbose_name='Familia de Producto'),
        ),
    ]
