# Generated by Django 5.2.7 on 2025-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_delete_domserializer_alter_dom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='fecha_produccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='lider_produccion',
            field=models.CharField(blank=True, choices=[('SIN_LIDER', '-- Seleccione un lider --'), ('ALEX_AREVALO', 'Alex Arevalo'), ('JULIO_MARTINEZ', 'Julio Martinez'), ('LUIS_MANRIQUE', 'Luis Manrique'), ('JHON_MOTERREY', 'Jhon Monterrey')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='orden_produccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
