# Generated by Django 5.2.7 on 2026-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_cliente_nit_familiaproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pausatiempoproduccion',
            name='minutos_pausados',
        ),
        migrations.RemoveField(
            model_name='registrotiempoproduccion',
            name='total_minutos_pausados',
        ),
        migrations.AddField(
            model_name='pausatiempoproduccion',
            name='segundos_pausados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Segundos de Pausa'),
        ),
        migrations.AddField(
            model_name='registrotiempoproduccion',
            name='total_segundos_pausados',
            field=models.IntegerField(default=0, verbose_name='Total segundos pausados'),
        ),
    ]
