# Generated by Django 5.2.7 on 2026-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_pausatiempoproduccion_minutos_pausados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapredefinida',
            name='tipo',
            field=models.CharField(choices=[('RESPONSABLE', 'Responsables'), ('LIDER_PLANTA', 'Líderes de Planta'), ('LIDER_ALMACEN', 'Líderes de Almacén'), ('TIPO_ESTADO_DOM', 'Tipos de Estado DOM'), ('OBJETIVO_PLANEACION', 'Objetivos de Planeación'), ('TIPO_MADERA', 'Tipos de Madera'), ('EMPAQUE_SERVICIO', 'Tipos de Empaque/Servicio'), ('TIPO_NEGOCIACION', 'Tipos de Negociación')], db_index=True, max_length=50, verbose_name='Tipo de Listado'),
        ),
    ]
