# Generated by Django 5.2.7 on 2025-11-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_dom_fecha_entrega_alter_dom_fecha_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='cantidad_elaborada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='cantidad_pendiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='cliente_recoge',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='fecha_tratamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='lider_almacen',
            field=models.CharField(blank=True, choices=[('SIN_LIDER', '-- Seleccione un lider --'), ('ALEX_AREVALO', 'Alex Arevalo'), ('JULIO_MARTINEZ', 'Julio Martinez'), ('LUIS_MANRIQUE', 'Luis Manrique'), ('JHON_MOTERREY', 'Jhon Monterrey')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='mudar_entrega',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='orden_tratamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dom',
            name='peso_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
