# Generated by Django 5.2.7 on 2026-04-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_listapredefinida_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se registran los operarios para este turno', verbose_name='Fecha del turno')),
                ('numero_operarios', models.IntegerField(help_text='Total de operarios disponibles en este turno para esta fecha', verbose_name='Número de operarios')),
                ('horas_extras', models.BooleanField(default=False, help_text='se agregan 120 minutos adicionales a la capacidad del turno', verbose_name='Horas extras')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_dia_registrados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registros_diarios', to='server.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Registro de turno del día',
                'verbose_name_plural': 'Registros de turno del día',
                'db_table': 'registros_turno_dia',
                'ordering': ['-fecha', 'turno'],
                'unique_together': {('turno', 'fecha')},
            },
        ),
    ]
