# Generated by Django 5.2.7 on 2026-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_registroturnodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriadom',
            name='campos_modificados',
            field=models.JSONField(blank=True, help_text='JSON: {"campo": {"antes": "valor_anterior", "despues": "valor_nuevo"}', null=True, verbose_name='Campos Modificados'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='fecha_asignacion_dom',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha asignación DOM'),
        ),
    ]
