# Generated by Django 5.2.7 on 2026-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_auditoriadom_campos_modificados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriadom',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edicion'), ('BLOQUEO_ETAPA', 'Bloqueo de Etapa'), ('DESBLOQUEO_ETAPA', 'Desbloqueo de Etapa'), ('ELIMINACION', 'Eliminación')], max_length=30, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='campana_venta',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='DOM generado en campaña de venta'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='dom_entregado_ok',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿DOM entregado según planeación?'),
        ),
        migrations.AlterField(
            model_name='registroalmacen',
            name='materias_primas',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Materias Primas Internas Procesadas'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='cliente_recoge',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Cliente recoge productos?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='control_tiempo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Producto lleva control de tiempo de corte y ensamble en armadora?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='encartonar',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Encartonar?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='grafado_fundas',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Productos requieren grafado y/o elaboración fundas?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='materia_prima_disponible',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Matería Prima Disponible'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='mudar_entrega',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Mudar de Colombia entrega productos?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='peso',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Productos requieren ser pesados?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='sello_ica',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Productos cuentan ya con sello ICA?'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='tratamiento_termico',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Tratamiento térmico realizado?'),
        ),
        migrations.AlterField(
            model_name='registroproduccion',
            name='segun_planeacion',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Actividades de producción realizadas según planeación de este DOM?'),
        ),
        migrations.AlterField(
            model_name='registrotratamiento',
            name='dom_con_tratamiento',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Tratamiento Fitosanitario realizado respecto de este DOM?'),
        ),
        migrations.AlterField(
            model_name='registrotratamiento',
            name='tratamiento_segun_planeacion',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Tratamiento termico realizado según planeación para este DOM?'),
        ),
    ]
