# Generated by Django 5.2.7 on 2026-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_nullable_booleans_eleccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroalmacen',
            name='numero_registro',
            field=models.IntegerField(verbose_name='Número de Registro'),
        ),
        migrations.AlterField(
            model_name='registrotratamiento',
            name='numero_registro',
            field=models.IntegerField(verbose_name='Numero de Registro'),
        ),
    ]
