# Generated by Django 5.2.7 on 2026-06-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_remove_default_numero_registro_almacen_tratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroplaneacion',
            name='cantidad_pedido',
        ),
        migrations.RemoveField(
            model_name='registroplaneacion',
            name='dom_producto',
        ),
        migrations.CreateModel(
            name='ProductoPlaneacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_proyectada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad proyectada a elaborar')),
                ('dom_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_planeacion', to='server.productosdom', verbose_name='Producto del DOM')),
                ('registro_planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_planeacion', to='server.registroplaneacion', verbose_name='Registro de Planeación')),
            ],
            options={
                'verbose_name': 'Producto de Planeación',
                'verbose_name_plural': 'Productos de Planeación',
                'db_table': 'productos_planeacion',
                'unique_together': {('registro_planeacion', 'dom_producto')},
            },
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='producto_planeacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='registros_produccion', to='server.productoplaneacion', verbose_name='Producto de Planeación'),
        ),
    ]
