# Generated by Django 5.2.7 on 2026-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_productos_planeacion_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplaneacion',
            name='minutos_totales',
            field=models.IntegerField(blank=True, choices=[(480, '8 horas (480 min)'), (600, '10 horas (600 min)')], null=True, verbose_name='Duración del turno'),
        ),
        migrations.AddField(
            model_name='registroplaneacion',
            name='numero_operarios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de operarios'),
        ),
    ]
