# Generated by Django 5.2.7 on 2026-06-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_numero_operarios_minutos_totales_planeacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroplaneacion',
            name='minutos_totales',
        ),
        migrations.RemoveField(
            model_name='registroplaneacion',
            name='numero_operarios',
        ),
        migrations.RemoveField(
            model_name='registroturnodia',
            name='horas_extras',
        ),
        migrations.AddField(
            model_name='registroturnodia',
            name='minutos_totales',
            field=models.IntegerField(choices=[(480, '8 horas (480 min)'), (600, '10 horas (600 min)')], default=480, help_text='Duración total del turno en minutos', verbose_name='Duración del turno'),
        ),
    ]
