# Generated by Django 5.2.7 on 2026-06-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_refactor_registro_turno_dia_minutos_totales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproduccion',
            name='cantidad_elaborada',
        ),
        migrations.RemoveField(
            model_name='registroproduccion',
            name='producto_planeacion',
        ),
        migrations.CreateModel(
            name='ProductoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_elaborada', models.IntegerField(verbose_name='Cantidad elaborada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto_planeacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_produccion', to='server.productoplaneacion', verbose_name='Producto de Planeación')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_produccion_registrados', to=settings.AUTH_USER_MODEL)),
                ('registro_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_produccion', to='server.registroproduccion', verbose_name='Registro de Producción')),
            ],
            options={
                'verbose_name': 'Producto de Producción',
                'verbose_name_plural': 'Productos de Producción',
                'db_table': 'productos_produccion',
                'ordering': ['registro_produccion', 'fecha_registro'],
            },
        ),
    ]
