# Generated by Django 5.2.7 on 2026-06-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_producto_produccion_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplaneacion',
            name='marcado_cliente',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Productos llevan marcas o símbolos del cliente?'),
        ),
    ]
