# Generated by Django 5.2.7 on 2026-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_registroplaneacion_marcado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroplaneacion',
            name='orden_tratamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden Tratamiento'),
        ),
    ]
