# Generated by Django 5.2.7 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_registroplaneacion_orden_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Factura de venta'),
        ),
    ]
