# Generated by Django 5.2.7 on 2026-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_dom_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='cantidad_empaques',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad de empaques que se despachan a las instalaciones del cliente'),
        ),
    ]
