# Generated by Django 5.2.7 on 2026-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_dom_cantidad_empaques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='materiales_externos',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Este DOM requiere materiales externos (SI/NO)'),
        ),
        migrations.AlterField(
            model_name='registroalmacen',
            name='dom_realizado_planeacion',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='¿Actividades de almacen realizadas según planeacion de la producción?'),
        ),
    ]
