# Generated by Django 5.2.7 on 2026-07-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_registrotratamiento_numero_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroturnodia',
            name='minutos_totales',
            field=models.IntegerField(choices=[(420, '7 horas (420 min)'), (540, '9 horas (540 min)')], default=420, help_text='Duración total del turno en minutos', verbose_name='Duración del turno'),
        ),
    ]
