# Generated by Django 5.2.7 on 2026-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_registroturnodia_minutos_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('GERENCIA', 'Gerencia'), ('ADMIN', 'Administrador'), ('ANALISTA_1', 'Analista Costos 1'), ('ANALISTA_2', 'Analista Costos 2'), ('PLANEADOR', 'Planeador'), ('LIDER_PLANTA', 'Líder de Planta')], max_length=20, verbose_name='Rol'),
        ),
    ]
