# Generated by Django 5.2.7 on 2026-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoplaneacion',
            name='tiempo_unitario_aplicado',
            field=models.IntegerField(blank=True, help_text='Minutos por unidad vigentes en el catálogo cuando se proyectó esta cantidad. Se copia una sola vez y no se actualiza: congela el estándar para que el histórico no cambie si el catálogo cambia.', null=True, verbose_name='Tiempo unitario aplicado'),
        ),
        migrations.AddField(
            model_name='productosdom',
            name='tiempo_unitario_aplicado',
            field=models.IntegerField(blank=True, help_text='Minutos por unidad vigentes en el catálogo cuando se registró este producto en el DOM. Se copia una sola vez y no se actualiza: congela el estándar para que el histórico no cambie si el catálogo cambia.', null=True, verbose_name='Tiempo unitario aplicado'),
        ),
    ]
