# Generated by Django 5.2.7 on 2026-08-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_alter_registroturnodia_minutos_totales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='minutos_totales',
        ),
    ]
