# Generated by Django 5.2.7 on 2026-08-13 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_remove_turno_minutos_totales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriadom',
            name='agente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='auditoriadom',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen'),
        ),
        migrations.AlterField(
            model_name='auditoriadom',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
