# Generated by Django 5.2.7 on 2026-08-16 09:50

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_auditoriadom_agente_auditoriadom_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='cantidad_empaques',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='cantidad de empaques que se despachan a las instalaciones del cliente'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='tiempo_salida_almacen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Tiempo de salida de almacen (minutos)'),
        ),
        migrations.AlterField(
            model_name='pausatiempoproduccion',
            name='segundos_pausados',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Segundos de Pausa'),
        ),
        migrations.AlterField(
            model_name='productoplaneacion',
            name='cantidad_proyectada',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Cantidad proyectada a elaborar'),
        ),
        migrations.AlterField(
            model_name='productoplaneacion',
            name='tiempo_unitario_aplicado',
            field=models.IntegerField(blank=True, help_text='Minutos por unidad vigentes en el catálogo cuando se proyectó esta cantidad. Se copia una sola vez y no se actualiza: congela el estándar para que el histórico no cambie si el catálogo cambia.', null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Tiempo unitario aplicado'),
        ),
        migrations.AlterField(
            model_name='productoproduccion',
            name='cantidad_elaborada',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Cantidad elaborada'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tiempo_produccion_unitario',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Tiempo de producción de una unidad en minutos'),
        ),
        migrations.AlterField(
            model_name='productosdom',
            name='cantidad_pedido',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Cantidad del pedido'),
        ),
        migrations.AlterField(
            model_name='productosdom',
            name='tiempo_unitario_aplicado',
            field=models.IntegerField(blank=True, help_text='Minutos por unidad vigentes en el catálogo cuando se registró este producto en el DOM. Se copia una sola vez y no se actualiza: congela el estándar para que el histórico no cambie si el catálogo cambia.', null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Tiempo unitario aplicado'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='orden_produccion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Orden de producción en fecha planeada'),
        ),
        migrations.AlterField(
            model_name='registroplaneacion',
            name='orden_tratamiento',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Orden Tratamiento'),
        ),
        migrations.AlterField(
            model_name='registroproduccion',
            name='minutos_asignados',
            field=models.IntegerField(blank=True, help_text='Este campo se comoleta automaticamente al momento de darle finalizar al cronometro', null=True, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Minutos asignados DOM'),
        ),
        migrations.AlterField(
            model_name='registroproduccion',
            name='numero_personas_asignadas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Número de personas asignadas a la producción de este DOM'),
        ),
        migrations.AlterField(
            model_name='registrotiempoproduccion',
            name='minutos_totales',
            field=models.IntegerField(blank=True, help_text='calculo se obtiene al darle finalizado a la producción', null=True, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Minutos totales'),
        ),
        migrations.AlterField(
            model_name='registrotiempoproduccion',
            name='total_segundos_pausados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='No puede ser negativo')], verbose_name='Total segundos pausados'),
        ),
        migrations.AlterField(
            model_name='registroturnodia',
            name='numero_operarios',
            field=models.IntegerField(help_text='Total de operarios disponibles en este turno para esta fecha', validators=[django.core.validators.MinValueValidator(1, message='Debe ser mayor a 0')], verbose_name='Número de operarios'),
        ),
        migrations.AddConstraint(
            model_name='dom',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_salida_almacen__gte', 0), ('tiempo_salida_almacen__isnull', True), _connector='OR'), name='doms_tiempo_salida_almacen_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='dom',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_empaques__gte', 1), ('cantidad_empaques__isnull', True), _connector='OR'), name='doms_cantidad_empaques_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='pausatiempoproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('segundos_pausados__gte', 0), ('segundos_pausados__isnull', True), _connector='OR'), name='pausas_tiempo_produccion_segundos_pausados_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='productoplaneacion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_proyectada__gte', 0), ('cantidad_proyectada__isnull', True), _connector='OR'), name='productos_planeacion_cantidad_proyectada_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='productoplaneacion',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_unitario_aplicado__gte', 1), ('tiempo_unitario_aplicado__isnull', True), _connector='OR'), name='productos_planeacion_tiempo_unitario_aplicado_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='productoproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_elaborada__gte', 0)), name='productos_produccion_cantidad_elaborada_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_produccion_unitario__gte', 1)), name='productos_tiempo_produccion_unitario_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='productosdom',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_pedido__gte', 1)), name='dom_productos_cantidad_pedido_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='productosdom',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_unitario_aplicado__gte', 1), ('tiempo_unitario_aplicado__isnull', True), _connector='OR'), name='dom_productos_tiempo_unitario_aplicado_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='registroplaneacion',
            constraint=models.CheckConstraint(condition=models.Q(('orden_produccion__gte', 1), ('orden_produccion__isnull', True), _connector='OR'), name='registros_planeacion_orden_produccion_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='registroplaneacion',
            constraint=models.CheckConstraint(condition=models.Q(('orden_tratamiento__gte', 1), ('orden_tratamiento__isnull', True), _connector='OR'), name='registros_planeacion_orden_tratamiento_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='registroproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_asignados__gte', 0), ('minutos_asignados__isnull', True), _connector='OR'), name='registros_produccion_minutos_asignados_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='registroproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('numero_personas_asignadas__gte', 1), ('numero_personas_asignadas__isnull', True), _connector='OR'), name='registros_produccion_numero_personas_asignadas_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
        migrations.AddConstraint(
            model_name='registrotiempoproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('total_segundos_pausados__gte', 0)), name='registros_tiempo_produccion_total_segundos_pausados_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='registrotiempoproduccion',
            constraint=models.CheckConstraint(condition=models.Q(('minutos_totales__gte', 0), ('minutos_totales__isnull', True), _connector='OR'), name='registros_tiempo_produccion_minutos_totales_no_negativo', violation_error_message='No puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='registroturnodia',
            constraint=models.CheckConstraint(condition=models.Q(('numero_operarios__gte', 1)), name='registros_turno_dia_numero_operarios_mayor_que_cero', violation_error_message='Debe ser mayor a 0'),
        ),
    ]
