# Generated by Django 5.2.7 on 2026-08-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_alter_dom_cantidad_empaques_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoproduccion',
            unique_together={('registro_produccion', 'producto_planeacion')},
        ),
    ]
