# Generated by Django 5.2.7 on 2026-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_alter_productoproduccion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroturnodia',
            name='minutos_totales',
            field=models.IntegerField(choices=[(420, '7 horas (420 min)'), (480, '8 horas (480 min)'), (510, '8 horas 30 min (510 min)'), (540, '9 horas (540 min)'), (600, '10 horas (600 min) — jornada anterior')], default=420, help_text='Duración total del turno en minutos', verbose_name='Duración del turno'),
        ),
    ]
