# Generated by Django 5.2.7 on 2026-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_alter_registroturnodia_minutos_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotiempoproduccion',
            name='cerrado_por_sistema',
            field=models.DateTimeField(blank=True, help_text='Instante en que el barrido cerró el cronómetro. Distinto de fin, que es cuando dejó de ser creíble.', null=True, verbose_name='Cerrado por el sistema'),
        ),
        migrations.AddField(
            model_name='registrotiempoproduccion',
            name='motivo_cierre',
            field=models.CharField(blank=True, choices=[('TECHO_JORNADA', 'Superó el tope de la jornada'), ('PAUSA_ABANDONADA', 'Pausa abandonada')], max_length=20, null=True, verbose_name='Motivo del cierre automático'),
        ),
        migrations.AlterField(
            model_name='auditoriadom',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edicion'), ('BLOQUEO_ETAPA', 'Bloqueo de Etapa'), ('DESBLOQUEO_ETAPA', 'Desbloqueo de Etapa'), ('ELIMINACION', 'Eliminación'), ('CIERRE_AUTOMATICO', 'Cierre automático')], max_length=30, verbose_name='Acción'),
        ),
    ]
