# Generated by Django 5.2.7 on 2026-09-09 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_registrotiempoproduccion_cerrado_por_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotiempoproduccion',
            name='revisado_en',
            field=models.DateTimeField(blank=True, help_text='Instante en que alguien declaró haber atendido este cierre automático.', null=True, verbose_name='Revisado el'),
        ),
        migrations.AddField(
            model_name='registrotiempoproduccion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, help_text='Quién lo atendió. Con revisado_en lleno nunca es nulo: una revisión sin autor no dice nada.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cronometros_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='registrotiempoproduccion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
