# Generated by Django 5.2.7 on 2026-09-11 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_registrotiempoproduccion_revisado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cliente activo'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='tipo_estado_dom',
            field=models.CharField(help_text='Referencia a ListaPredifinida tipo=TIPO:ESTADO:DOM', max_length=100, verbose_name='Tipo o Estado del DOM'),
        ),
        migrations.AlterField(
            model_name='familiaproducto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Familia activa'),
        ),
        migrations.AlterField(
            model_name='listapredefinida',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='listapredefinida',
            name='tipo',
            field=models.CharField(choices=[('RESPONSABLE', 'Responsables'), ('LIDER_PLANTA', 'Líderes de Planta'), ('LIDER_ALMACEN', 'Líderes de Almacén'), ('TIPO_ESTADO_DOM', 'Tipos de Estado DOM'), ('OBJETIVO_PLANEACION', 'Objetivos de Planeación'), ('TIPO_MADERA', 'Tipos de Madera'), ('EMPAQUE_SERVICIO', 'Tipos de Empaque/Servicio'), ('TIPO_NEGOCIACION', 'Tipos de Negociación')], max_length=50, verbose_name='Tipo de Listado'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Producto_activo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Turno activo'),
        ),
        migrations.AddIndex(
            model_name='dom',
            index=models.Index(condition=models.Q(('dom_liberado_cierre', False)), fields=['dom_id'], name='dom_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotiempoproduccion',
            index=models.Index(condition=models.Q(('estado', 'FINALIZADO'), _negated=True), fields=['inicio'], name='crono_abierto_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotiempoproduccion',
            index=models.Index(condition=models.Q(('cerrado_por_sistema__isnull', False), ('revisado_en__isnull', True)), fields=['cerrado_por_sistema'], name='crono_sin_revisar_idx'),
        ),
    ]
